### ISSUE TITLE
Got the running errors

### ISSUE THREAD

**Issue by LifangHe** [neu-spiral/iROPASSISTPackage#1]
After installing all the required packages by following the instructions and run the command in the terminal:

python mainScript.py "example/" "exampleImages.xlsx" "scoresOfExampleImages.xlsx" 

I got the running errors as follows:

Traceback (most recent call last):
  File "mainScript.py", line 114, in <module>
    unetCNN = SegmentUnet(cnnModel,cnnSegmentationsPath)
  File "segmentation_package/segment_unet.py", line 26, in __init__
    self.model = load_model(unet_dir)
  File "segmentation_package/models.py", line 25, in load_model
    model = model_from_json(open(model_arch).read())
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/models.py", line 197, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/engine/topology.py", line 2375, in from_config
    process_layer(layer_data)
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/engine/topology.py", line 2372, in process_layer
    layer(input_tensors)
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/engine/topology.py", line 1337, in __call__
    node_indices, tensor_indices)
  File "/Users/XXX/opt/anaconda2/envs/py2/lib/python2.7/site-packages/keras/engine/topology.py", line 1253, in _arguments_validation
    'Layer shapes: %s' % (input_shapes))
Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 256, 24, 12), (None, 64, 24, 24)]

**Comment by LifangHe** [comment]
Finally, I fixed this issue by doing some configurations and changes as follows:

1) Install package versions
pip install keras==2.1.6
pip install tensorflow==1.0.0
pip install theano==1.0.3
pip install sklearn==0.20.4
pip install configparser
pip install numpy==1.12.0

2) Change the keras.json file to
vim ~/.keras/keras.json
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "tensorflow",
    "image_data_format": "channels_first"
}

3) Add the below code to the "mainScript.py" file

import tensorflow as tf
tf.python.control_flow_ops = tf

4) Change the unet_architecture.json file by replacing "Merge" with "Concatenate". The changed results are the following:

{"class_name": "Concatenate", "config": {"name": "merge_1", "axis": 1}
{"class_name": "Concatenate", "config": {"name": "merge_2", "axis": 1}

**Note**: this file is exactly the same as for retina-unet code, I have used this changed file to run through the retina-unet code as well.

5) Make the following changes to the "featureExtractionScript.py" file:

(a) Change "from sklearn.mixture import GMM" to "from sklearn.mixture import GaussianMixture as GMM"

(b) Change
"feats=np.concatenate((feats,cov[0]))
feats=np.concatenate((feats,cov[1]))"
to
"feats=np.concatenate((feats,cov[0][0]))
feats=np.concatenate((feats,cov[1][0]))“

Cheers!! 👏👏👏
